### ISSUE TITLE
#search_form * in index.css

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2348]
This is really bad. css gets analyzed from right to left, which means this line of css causes parsers to check every single element (*), and then analyze the parent to see if it has the search_form id.

Thankfully this seems to be the only instance of this. I will try to get to it after I am finished with splitting the root and _light stuff appropriately.

**Comment by joshuaadickerson** [comment]
From my understanding, id selectors come first.

**Comment by eurich** [comment]
should be an easy fix:
replace

``` css 
#search_form * {
    margin: 0;
    border-radius: 0;
    float: left;
}
```
with 
``` css 
#search_form label, #search_form input {
    margin: 0;
    border-radius: 0;
    float: left;
}
```
